apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services appset
  namespace: argocd
spec:
  generators:
    git:
      repoURL: your repository url
      revision: main
      directories:
        path: services/*
  template:
    metadata:
      name: path.basename
    spec:
      project: arms simulation
      source:
        repoURL: your repository url
        targetRevision: main
        path: path/chart
        helm:
          valueFiles:
            values.yaml
      destination:
        server: https kubernetes default svc
        namespace: your namespace
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
