# Generated by Terraform on apply — no pre-existing key pair required as input.
resource "tls_private_key" "jenkins_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "jenkins_key" {
  key_name   = "jenkins-key-${formatdate("YYYYMMDDhhmmss", timestamp())}"
  public_key = tls_private_key.jenkins_key.public_key_openssh

  lifecycle {
    ignore_changes = [key_name]
  }
}

# Private key written locally so it's usable for SSH right after apply.
# Restricted to owner-read-only; excluded from git via .gitignore (*.pem).
resource "local_file" "jenkins_private_key" {
  content         = tls_private_key.jenkins_key.private_key_pem
  filename        = "${path.module}/jenkins-key.pem"
  file_permission = "0400"
}
